import puppeteer from 'puppeteer';

export const flyerService = {
  /**
   * Generates a flyer based on template and data
   * @param {string} templateId - The ID of the template to use
   * @param {object} data - The content data for the flyer
   * @returns {Promise<Buffer>} - The generated PDF/Image buffer
   */
  async generateFlyer(templateId, data) {
    // eslint-disable-next-line no-console
    console.log('Generating flyer');

    // In a real app, we would load an EJS/HTML template here.
    // For this POC, we will construct a simple HTML string.
    const htmlContent = this._generateHtml(templateId, data);

    let browser = null;
    try {
      browser = await puppeteer.launch({
        headless: 'new',
        args: ['--no-sandbox', '--disable-setuid-sandbox']
      });
      const page = await browser.newPage();

      // Set viewport for a standard flyer size (e.g., A4 approx)
      await page.setViewport({ width: 794, height: 1123 });

      await page.setContent(htmlContent, { waitUntil: 'networkidle0' });

      // Generate PDF
      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true
      });

      return {
        buffer: pdfBuffer,
        contentType: 'application/pdf',
        filename: `flyer-${Date.now()}.pdf`
      };

    } catch (error) {
      console.error('Puppeteer generation error:', error);
      throw new Error('Failed to generate flyer PDF');
    } finally {
      if (browser) {
        await browser.close();
      }
    }
  },

  /**
   * Helper to generate HTML string (Mock Template Engine)
   */
  _generateHtml(templateId, data) {
    const { title, description, contact, colorScheme } = data;

    // Basic styles based on templateId
    let bgStyle = 'background-color: #ffffff;';
    let fontStyle = 'font-family: sans-serif;';
    let accentColor = '#d32f2f';

    if (templateId === 'cheesy-pig') {
      bgStyle = 'background-color: #ffe6e6;'; // Pinkish
      fontStyle = 'font-family: "Comic Sans MS", cursive, sans-serif;';
    } else if (templateId === 'business-classic') {
      bgStyle = 'background-color: #f8f9fa;'; // Light grey
      fontStyle = 'font-family: "Times New Roman", Times, serif;';
    }

    if (colorScheme === 'green') {
      accentColor = '#2e7d32';
    } else if (colorScheme === 'blue') {
      accentColor = '#1565c0';
    } else if (colorScheme === 'purple') {
      accentColor = '#6a1b9a';
    }

    return `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { margin: 0; padding: 40px; ${bgStyle} ${fontStyle} color: #333; }
          .container { max-width: 800px; margin: 0 auto; border: 1px solid #ddd; padding: 40px; background: white; }
          h1 { color: ${accentColor}; font-size: 48px; text-align: center; margin-bottom: 20px; }
          p { font-size: 24px; line-height: 1.6; margin-bottom: 30px; }
          .contact { margin-top: 50px; padding-top: 20px; border-top: 2px solid #333; font-weight: bold; text-align: center; font-size: 20px; }
          .footer { margin-top: 40px; text-align: center; font-size: 12px; color: #888; }
        </style>
      </head>
      <body>
        <div class="container">
          <h1>${title || 'Untitled Flyer'}</h1>

          <div class="content">
            <p>${description || 'No description provided.'}</p>
          </div>

          <div class="contact">
            Contact: ${contact || 'N/A'}
          </div>

          <div class="footer">
            Generated by FlairForge - Template: ${templateId}
          </div>
        </div>
      </body>
      </html>
    `;
  }
};
